### ISSUE TITLE
Playlist in old YouTube (polymer disabled)

### ISSUE THREAD

**Issue by krystian3w** [Zren/ResizeYoutubePlayerToWindowSize#37]
>![obraz](https://user-images.githubusercontent.com/35370833/39086559-a0e1862a-4593-11e8-8080-9bd0ead92d07.png) |
> --- |

`https://www.youtube.com/watch?v=37StRy0LEbI&list=PLFgquLnL59ak5FwmTB7DRJqX3M2B1D7xI`

Old layout recover with cookies (and disable script):

* https://cable.ayra.ch/tampermonkey/view.php?script=youtube_old_design.user.js
* https://greasyfork.org/pl/scripts/32906-get-me-old-youtube

---

In polymer (material) version list is positioned OK.

**Comment by Zren** [comment]
I don't really want to have to support every single version of YouTube... I don't think the older version of my script work anymore though, so I can't tell you to use v87.

We basically need to add this CSS:

```css
body.ytwp-window-player #player .player-height#watch-appbar-playlist {
    left: calc((100vw - 1066px)/2 + 640px + 10px);
    width: 416px;
}

@media screen and (min-height: 630px) and (min-width: 1294px) {
    body.ytwp-window-player #player .player-height#watch-appbar-playlist {
        left: calc((100vw - 1280px)/2 + 854px + 10px);
        width: 416px;
    }
}

@media screen and (min-width: 1720px) and (min-height:980px) {
    body.ytwp-window-player #player .player-height#watch-appbar-playlist {
        left: calc((100vw - 1706px)/2 + 1280px + 10px);
        width: 416px;
    }
}
```
