### ISSUE TITLE
Thumbnails stopped appearing

### ISSUE THREAD

**Issue by iPaulis** [Zren/ResizeYoutubePlayerToWindowSize#41]
Browser Name: Firefox

Browser Version: 59.0.3 (64-bit) and 61.0.2 (64-bit)

Operating System: Windows 10 (64-bit) and Linux Mint 18.3 (64-bit)

Software Version: 118

Problem Description: I use the Iridium plugin and also this userscript. Everything was working fine until about 2 weeks ago, when the thumbnails stopped showing up after loading a video with autoplay disabled.
I don't know why, but for some reason both scripts are not interacting properly with each other.
When I disable the Resize script, then Iridium loads the thumbnail correctly, but when I activate this script too, the background goes black. 

Steps to reproduce:

    1. Have both Iridium (v0.2.1) and Resize YT To Window Size (v118 from GreasyFork and Greasemonkey v4.6) installed.
    2. Disable autoplay in Iridium.
    3. Load any youtube video and the thumbnail wont show up, just a black background instead.

Let me know if there is any other info I could provide.
Thank you in advance.

**Comment by Zren** [comment]
Which thumbnails?

![](https://i.imgur.com/h6hL9Io.png)

![](https://i.imgur.com/RmqZHE0.png)

The sidebar thumbnails are showing up for me.

It's possible were using different "versions" of YouTube though.

What's your `VISITOR_INFO1_LIVE` and `PREF` cookie?

Right Click webpage > Inspect Element > Storage > ...

**Comment by Zren** [comment]
Do you mean the "large thumbnail" for the current video which is showing up as a black rectangle in my firefox screenshot?

**Comment by Zren** [comment]
Looks like `.ytp-cued-thumbnail-overlay` needs a `z-index: 10`.

And the `.player-theater-container` also needs to override the following CSS rule so that it doesn't show a white box when the video player moves to the miniplayer in the bottom right.

```css
ytd-watch-flexy[theater] #player-theater-container.ytd-watch-flexy,
ytd-watch-flexy[fullscreen] #player-theater-container.ytd-watch-flexy {
    height: calc((9 / 16) * 100vw);
    max-height: calc(100vh - 185px);
}
```
