### ISSUE TITLE
Please make this script working with m.youtube.com

### ISSUE THREAD

**Issue by DarKWinGTM** [Zren/ResizeYoutubePlayerToWindowSize#59]
https://m.youtube.com/watch?v=DTtmhLnx208 loading low resource when opening on Web Browser ex:waterfox. I would like to using this script on my setup.

**Comment by DarKWinGTM** [comment]
https://imgur.com/gEbR2xM.png

**Comment by Zren** [comment]
In order to avoid the redirect, we needed to add `?app=m` to the url: https://m.youtube.com/watch?v=DTtmhLnx208&app=m

This... is a little out of scope of this script. I didn't support gaming.youtube.com either in Issue #15. That said, I can help you create some CSS you can put into the Sylus extension: https://addons.mozilla.org/en-CA/firefox/addon/styl-us/

The following works for portrait mode:

```css
html {
    scrollbar-width: none;
}
#player-container-id {
    position: static !important;
}
#player-container-id .player-size {
    padding-bottom: 100vh;
}
ytm-app.sticky-player {
    padding-top: 0px !important;
}
ytm-app ytm-watch .player-size {
    padding-bottom: 0 !important;
}
ytm-mobile-topbar-renderer.sticky-player.in:not(:hover) {
    opacity: 0;
}
```

We still need to fix landscape mode though.

**Comment by Zren** [comment]
This works for landscape. It fixes the other videos sidebar position:

```css
@-moz-document domain("m.youtube.com") {
html {
    scrollbar-width: none;
}
#player-container-id {
    position: static !important;
}
#player-container-id .player-size {
    padding-bottom: 100vh;
}
ytm-app.sticky-player {
    padding-top: 0px !important;
}
ytm-app ytm-watch .player-size {
    padding-bottom: 0 !important;
}
ytm-mobile-topbar-renderer.sticky-player.in:not(:hover) {
    opacity: 0;
}

.scwnr-content > lazy-list {
    display: flex;
    flex-wrap: wrap;
}
.ytm-autonav-bar {
    width: 100%;
}

@media (orientation:landscape) {
    ytm-single-column-watch-next-results-renderer [section-identifier="related-items"] {
        position: static !important;
        width: 100%;
    }
    ytm-single-column-watch-next-results-renderer [section-identifier="related-items"] .item {
        width: 20vw;
    }
}
}
```
