### ISSUE TITLE
[BUG] Video title and partial description overlays the playing video

### ISSUE THREAD

**Issue by ctrl-alt-w** [Zren/ResizeYoutubePlayerToWindowSize#77]
Version: 131
I've tried to reinstall the extension and the script 
Tested in Vivaldi, Firefox using violentmonkey and greasemonkey, and i still get the same issue
![image](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/77025540/46512216-9704-41b2-8cfc-119ba9ed00ba)
as you can see on the scroll bar to the right, it might be related to #76

**Comment by evkaw** [comment]
anyone know an alternative?

**Comment by Zren** [comment]
I can reproduce in Chromium Incognito mode. This seems to fix it in DevTools.

```css
ytd-watch-flexy[theater] #player-wide-container.ytd-watch-flexy,
ytd-watch-flexy[fullscreen] #player-wide-container.ytd-watch-flexy {
    position: static;
    height: 0;
    min-height: 0;
}
```

**Comment by krystian3w** [comment]
fyi @pieters2 based on #78

**Comment by Simon-Tesla** [comment]
Also seeing this issue in Firefox, and can confirm that the above stylesheet fixes the issue there.

**Comment by lakshits11** [comment]
> 
> This CSS seems to fix it in DevTools.
> 
> ```css
> ytd-watch-flexy[theater] #player-wide-container.ytd-watch-flexy,
> ytd-watch-flexy[fullscreen] #player-wide-container.ytd-watch-flexy {
>     position: static;
>     height: 0;
>     min-height: 0;
> }
> ```


Hy, I implemented your solution and I am getting this:

![image](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/54276661/6a61d70e-fc04-40fd-acf1-8289debc9b1c)

A button or I dont know what below the arrow buttons

**Comment by Zren** [comment]
> Also seeing this issue in Firefox, and can confirm that the above stylesheet fixes the issue there.

Yep, noticed this too when eating dinner.

> Hy, I implemented your solution and I am getting this: A button or I dont know what below the arrow buttons

I noticed this in Light Mode:

![2023-06-28___23-21-39](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/416367/c0c57d52-6442-45ee-93ab-b9ad0107f76c)

So there's something going on.

**Comment by Zren** [comment]
Seems like it's part of the masthead/header.

![2023-06-28___23-25-21](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/416367/6454eb14-6263-4dd3-813e-237c3bb253ff)

It's normally hidden with:

```css
#skip-navigation.ytd-masthead {
    position: absolute;
    top: -1000px;
    background-color: var(--yt-spec-brand-background-primary);
}
```

So if the screen is smaller than `1000px` then it will be visible. I'll just add the following so it's always 1.5 screen height above.


```css
#skip-navigation.ytd-masthead {
    top: -150vw;
}
```
