### ISSUE TITLE
Youtube videos with long titles are now covering the search bar, also regardless of video title length the search bar is inaccessible.

### ISSUE THREAD

**Issue by jaredanson** [Zren/ResizeYoutubePlayerToWindowSize#88]
Even if the video has a short title that does not obscure the search bar, it is not clickable and inaccessible for typing. To use the search bar, you're required to exit the video by clicking the home button before accessing it.

**Comment by JonseyJones** [comment]
I confirm.

**Comment by krystian3w** [comment]
![obraz](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/35370833/971286f9-ef0a-4935-a6de-b29ae6951936)

**Comment by Zren** [comment]
For some reason `ytd-page-manager#page-manager { margin-top: 56px; }` isn't moving the div. The browser detects the margin, but that margin overlays the video.

```css
#page-manager.ytd-app {
  margin-top: var(--ytd-masthead-height,var(--ytd-toolbar-height)); /* = 56px */
}
```

If I add `#content { padding-top: 0px; }` it does nothing, but if I add `#content { padding-top: 1px; }` it moves the thing by `56px + 1px` for some reason.

If I add `#page-manager.ytd-app { padding-top: 56px; }` then it works too. Something is fucked here, but I've no clue what.

I'll just add the following to make it work.

```css
#page-manager.ytd-app {
  padding-top: var(--ytd-masthead-height,var(--ytd-toolbar-height));
}
```

**Comment by Zren** [comment]
Also it seems like my `56 + 15px = 71px` padding isn't working either.

```css
html:not([fullscreen="true"]) body.ytwp-window-player:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy, html:not([fullscreen="true"]) body.ytwp-window-player:not(.enhancer-for-youtube-pinned-player) ytd-watch-grid {
    padding-top: 71px;
}
```
